### ISSUE TITLE
What are the Goals of the Project?

### ISSUE THREAD

**Issue by grantmwilliams** [grantmwilliams/simple-web-server#1]
We should probably explicitly list out the goals of the project.  

Some ideas to start with:

1. What protocols should we support?
2. What benchmarks do we want to hit? (throughput / second, number of connections etc.)

**Comment by DLMousey** [comment]
I'd vote in the beginning just go full on MVP mode, support HTTP, listen on 80 and have some form of config that dictates what happens once the request has been received.

In terms of benchmarks number of connections would be neat to hit but i've not really got any specific goal in mind

**Comment by grantmwilliams** [comment]
It would be a cool goal to have no external dependencies i.e. only use the standard library of the language if possible (this is obviously easier or harder depending on the language we choose).

**Comment by grantmwilliams** [comment]
[RFC2616](https://www.ietf.org/rfc/rfc2616.txt)

**Comment by DLMousey** [comment]
Oh yeah, specs are a thing...  If we nail it down to absolute bare minimum and get _something_ working it won't feel like such a mountain to climb at least?
