### ISSUE TITLE
What language should we write this in?

### ISSUE THREAD

**Issue by grantmwilliams** [grantmwilliams/simple-web-server#2]
Some ideas:

1. Rust
2. Golang
3. Python
4. Erlang/Elixir
5. Scala
6. C
7. C++

Poll Here:
https://forms.gle/jC42S27ftRTmwrxB6

**Comment by nacleric** [comment]
Python

**Comment by grantmwilliams** [comment]
> Python

Any reason You want to do it in Python?

**Comment by nacleric** [comment]
No real reason besides wanting to write more python. Not sure how performant you want this tho. I don't really care about the specs tbh

I'd be down with rust or golang if others wanted to use it

**Comment by grantmwilliams** [comment]
You can make sure python is relatively performant. We'd just have to make heavy use of async and lazy operations.

**Comment by DLMousey** [comment]
My vote's for either Rust or Go, since they'd give us nutty performance and hey it's something new let's get out of our comfort zones

**Comment by nacleric** [comment]
Do you have a preference @grantmwilliams? I wouldn't mind Rust, Go, Python. Mousey wouldn't mind Rust, Go. This might bump out python depending if anyone else wants to participate. So I think we could go with your pick if your deciding between Rust and Golang. Unless other people from chat still have an opinion

**Comment by grantmwilliams** [comment]
I don't have any super strong preferences @nacleric.

Python would be easiest, but I might prefer to have a chance to learn a new language or practice a language I don't know well. But I definitely don't mind doing Python.

Rust, Scala, or C would be pretty cool.

Erlang/Elixir would be pretty idiomatic, but no one but me loves the languages.

Golang seems cool. No strong feelings either way with it.

**Comment by jmcardon** [comment]
Scala is a horrible choice, and I have experience on this front.

Rust is a good choice IMO, it's a fairly good experience in writing a fairly functional language that's also low level.

C can be a good choice but much harder (bug city).

C++ can also be ok if you don't venture into the wildlands of c++14 features.

> Erlang/Elixir would be pretty idiomatic, but no one but me loves the languages.

idk what you mean by idiomatic, it would be as idiomatic as writing any sort of parsing in an untyped language, so the structure of a good chunk of stuff might be kind of obnoxious to verify.

A typed language will make a lot of your invariants in your http model safer, since you'll have structural guarantees about what is or is not in a particular class/struct.

**Comment by nacleric** [comment]
![rustacean-flat-gesture](https://user-images.githubusercontent.com/14945333/68424199-7c814400-0171-11ea-94a1-9e3929ebac18.png)

**Comment by grantmwilliams** [comment]
> idk what you mean by idiomatic, it would be as idiomatic as writing any sort of parsing in an untyped language, so the structure of a good chunk of stuff might be kind of obnoxious to verify.

@jmcardon, I was more referring to the easy of concurrency in the BEAM/OPT languages. The standard library also makes it stupid easy to write a simple HTTP server. Admittedly the lack of types is pretty rough, but Erlang does have the upside of being one of the best languages I've ever used for working with binary data.

**Comment by grantmwilliams** [comment]
Lets vote on a language: https://forms.gle/jC42S27ftRTmwrxB6

**Comment by jmcardon** [comment]
> @jmcardon, I was more referring to the easy of concurrency in the BEAM/OPT languages. The standard library also makes it stupid easy to write a simple HTTP server. Admittedly the lack of types is pretty rough, but Erlang does have the upside of being one of the best languages I've ever used for working with binary data.

Concurrency when you have thread pools is fairly straight forward as well.I don't exactly know how rust tackles the problem though

**Comment by grantmwilliams** [comment]
Final Results:
![image](https://user-images.githubusercontent.com/10481809/68494247-b4d95e80-0213-11ea-9347-101be890d21d.png)
